import{a as p,i as a,S as h}from"./assets/vendor-lDhL-8I6.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&n(f)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();async function y(r,s=1,t={}){const n=t.perPage||15;try{const o=(await p.get("https://pixabay.com/api/",{params:{key:"49643182-9754596b7a63617f9fa0f6656",q:r,page:s,per_page:n,image_type:"photo",orientation:"horizontal",safesearch:!0,...t.extraParams}})).data;return o.hits.length===0&&a.show({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"}),{images:o.hits,totalHits:o.totalHits}}catch(e){throw a.show({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"}),console.error("API Error:",e),e}}const g=document.querySelector(".gallery");let u;function w(r){const s=r.map(t=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${t.largeImageURL}">
        <img
          class="gallery-image"
          src="${t.webformatURL}"
          alt="${t.tags}"
        />
      </a>
      <div class="info">
          <p><b>Likes</b> ${t.likes}</p>
          <p><b>Views</b> ${t.views}</p>
          <p><b>Comments</b> ${t.comments}</p>
          <p><b>Downloads</b> ${t.downloads}</p>
        </div>
    </li>`).join("");g.insertAdjacentHTML("beforeend",s),u?u.refresh():u=new h(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,scrollZoom:!0})}function b(){g.innerHTML=""}function L(){document.querySelector(".loader").classList.add("is-visible")}function B(){document.querySelector(".loader").classList.remove("is-visible")}function I(){document.querySelector(".MoreBtn").classList.add("is-visible")}function i(){document.querySelector(".MoreBtn").classList.remove("is-visible")}const O=document.querySelector(".form"),v=document.querySelector(".MoreBtn");let l="",c=1,d=15;O.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),l===""){a.warning({title:"Warning",message:"Please enter a search term.",position:"topRight",backgroundColor:"#ffa000",messageColor:"#fff",timeout:3e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"});return}i(),c=1,await m(l,c)});v.addEventListener("click",async()=>{c+=1,await m(l,c)});async function m(r,s){L(),s===1&&b();try{const{images:t,totalHits:n}=await y(r,s,{perPage:d});if(t.length===0&&s===1){i(),a.show({title:"No results",message:"Sorry, no images match your search query.",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"});return}if(w(t),s>1){const e=document.querySelector(".gallery").firstElementChild;if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"})}}t.length<d||s*d>=n?(i(),a.show({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"})):I()}catch(t){console.log("Fetch failed:",t),a.show({title:"Error",message:"Something went wrong while fetching images.",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"}),i()}finally{B()}}
//# sourceMappingURL=index.js.map
