import{a as g,i as f,S as m}from"./assets/vendor-lDhL-8I6.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();async function p(o,s=1,a={}){const r=a.perPage||15;try{const t=(await g.get("https://pixabay.com/api/",{params:{key:"49643182-9754596b7a63617f9fa0f6656",q:o,page:s,per_page:r,image_type:"photo",orientation:"horizontal",safesearch:!0,...a.extraParams}})).data;return t.hits.length===0&&f.show({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"}),{images:t.hits,totalHits:t.totalHits}}catch(e){throw f.show({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"}),console.error("API Error:",e),e}}const h=document.querySelector(".gallery");function y(o){const s=o.map(r=>`
  <li class="gallery-item">
    <a class="gallery-link" href="${r.largeImageURL}">
      <img
        class="gallery-image"
        src="${r.webformatURL}"
        alt="${r.tags}"
      />
    </a>
    <div class="info">
        <p><b>Likes</b> ${r.likes}</p>
        <p><b>Views</b> ${r.views}</p>
        <p><b>Comments</b> ${r.comments}</p>
        <p><b>Downloads</b> ${r.downloads}</p>
      </div>
  </li>`).join("");h.insertAdjacentHTML("beforeend",s),new m(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,scrollZoom:!0}).refresh()}function b(){const o=document.querySelector(".gallery");o.innerHTML=""}function w(){document.querySelector(".loader").classList.add("is-visible")}function L(){document.querySelector(".loader").classList.remove("is-visible")}function B(){document.querySelector(".MoreBtn").classList.add("is-visible")}function c(){document.querySelector(".MoreBtn").classList.remove("is-visible")}const v=document.querySelector(".form"),I=document.querySelector(".MoreBtn");let i="",n=1,u=15;v.addEventListener("submit",async o=>{o.preventDefault(),i=o.target.elements["search-text"].value.trim(),i!==""&&(n=1,await d(i,n))});I.addEventListener("click",async()=>{n+=1,await d(i,n)});async function d(o,s){w(),s===1&&b();try{const{images:a,totalHits:r}=await p(o,s,{perPage:u});if(a.length===0&&s===1){c(),iziToast.show({title:"No results",message:"Sorry, no images match your search query.",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"});return}if(y(a),s>1){const e=document.querySelector(".gallery").firstElementChild;if(e){const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,left:0,behavior:"smooth"})}}a.length<u||s*u>=r?(c(),iziToast.show({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"})):B()}catch(a){console.log("Fetch failed:",a),iziToast.show({title:"Error",message:"Something went wrong while fetching images.",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"}),c()}finally{L()}}
//# sourceMappingURL=index.js.map
