import{a as w,i as d,S as v}from"./assets/vendor-Cgc9PhsO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function y(o){return o.map(({webformatURL:r,largeImageURL:a,tags:l,likes:e,views:t,comments:n,downloads:u})=>`
        <li class="gallery-item">
            <a href="${a}" class="gallery-link">
                <img src="${r}" alt="${l}" loading="lazy" />
            </a>
            <div class="info">
                <p class="info-item"><b>Likes</b> ${e}</p>
                <p class="info-item"><b>Views</b> ${t}</p>
                <p class="info-item"><b>Comments</b> ${n}</p>
                <p class="info-item"><b>Downloads</b> ${u}</p>
            </div>
        </li>
    `).join("")}function S(){const o=document.querySelector(".gallery");o&&(o.innerHTML="")}function m(){const o=document.querySelector(".loader");o&&(console.log("loader on"),o.classList.add("visible"))}function f(){const o=document.querySelector(".loader");o&&(console.log("loader off"),o.classList.remove("visible"))}const q="49643182-9754596b7a63617f9fa0f6656";async function g(o,r){return await w.get("https://pixabay.com/api/",{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})}document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".form"),r=document.querySelector("input[name='search-text']"),a=document.querySelector(".gallery"),l=document.querySelector(".loader"),e=document.querySelector(".MoreBtn");if(!o||!r||!a||!l||!e){console.error("Один або кілька DOM-елементів не знайдено.");return}let t=1,n=null,u=0;const h=15;l.style.display="none",e.style.display="none",o.addEventListener("submit",b),e.addEventListener("click",L);async function b(s){s.preventDefault();const c=r.value.trim();if(!c){d.warning({title:"Empty Query",message:"Please enter a search term!",position:"topRight"});return}t=1,S(),m();try{const i=await g(c,t);if(f(),!i.data.hits||i.data.hits.length===0){d.warning({title:"No Results",message:"No images found for your query. Try something else!",position:"topRight"}),e.style.display="none";return}u=i.data.totalHits,a.innerHTML=y(i.data.hits),p(),n?n.refresh():n=new v(".gallery a",{captions:!0,captionDelay:250,close:!0})}catch(i){f(),e.style.display="none",d.error({title:"Error",message:"Something went wrong. Please try again!",position:"topRight"}),console.error(i)}}async function L(){t++,e.disabled=!0,m();try{const s=await g(r.value.trim(),t);if(f(),e.disabled=!1,!s.data.hits||s.data.hits.length===0){p();return}a.insertAdjacentHTML("beforeend",y(s.data.hits)),p();const c=document.querySelectorAll(".gallery-item");if(c.length>0){const i=c[c.length-1].getBoundingClientRect().height;window.scrollBy({left:0,top:i*2,behavior:"smooth"})}n&&n.refresh()}catch(s){f(),e.style.display="none",d.error({title:"Error",message:"Something went wrong during loading.",position:"topRight"}),console.error(s)}}function p(){const s=Math.ceil(u/h);t>=s?(e.style.display="none",d.info({title:"End of Results",message:"You've reached the end of search results.",position:"topRight"})):e.style.display="block"}});
//# sourceMappingURL=index.js.map
